=== MTES-MCT/ecobalyse-data/data/schemas/lci-schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "additionalProperties": false,
  "properties": {
    "activityName": {
      "type": "string"
    },
    "categories": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "comment": {
      "type": "string"
    },
    "displayName": {
      "type": "string"
    },
    "elecMJ": {
      "minimum": 0,
      "type": "number"
    },
    "heatMJ": {
      "minimum": 0,
      "type": "number"
    },
    "id": {
      "format": "uuid",
      "type": "string"
    },
    "impacts": {
      "properties": {
        "acd": {
          "type": "number"
        },
        "cch": {
          "type": "number"
        },
        "etf": {
          "type": "number"
        },
        "etf-c": {
          "type": "number"
        },
        "fru": {
          "type": "number"
        },
        "fwe": {
          "type": "number"
        },
        "htc": {
          "type": "number"
        },
        "htc-c": {
          "type": "number"
        },
        "htn": {
          "type": "number"
        },
        "htn-c": {
          "type": "number"
        },
        "ior": {
          "type": "number"
        },
        "ldu": {
          "type": "number"
        },
        "mru": {
          "type": "number"
        },
        "ozd": {
          "type": "number"
        },
        "pco": {
          "type": "number"
        },
        "pma": {
          "type": "number"
        },
        "swe": {
          "type": "number"
        },
        "tre": {
          "type": "number"
        },
        "wtu": {
          "type": "number"
        }
      },
      "required": [
        "acd",
        "cch",
        "etf",
        "etf-c",
        "fru",
        "fwe",
        "htc",
        "htc-c",
        "htn",
        "htn-c",
        "ior",
        "ldu",
        "mru",
        "ozd",
        "pco",
        "pma",
        "swe",
        "tre",
        "wtu"
      ],
      "type": "object"
    },
    "landOccupation": {
      "type": "number"
    },
    "location": {
      "type": "string"
    },
    "massPerUnit": {
      "exclusiveMinimum": 0,
      "type": [
        "number",
        "null"
      ]
    },
    "metadata": {
      "items": {
        "properties": {
          "alias": {
            "type": "string"
          },
          "displayName": {
            "type": "string"
          },
          "forestManagement": {
            "enum": [
              "intensivePlantation",
              "sustainableManagement",
              "certifiedSustainableManagement",
              "diversifiedForest",
              "certifiedDiversifiedForest"
            ],
            "type": "string"
          },
          "id": {
            "format": "uuid",
            "type": "string"
          },
          "scopes": {
            "items": {
              "enum": [
                "food",
                "food2",
                "textile",
                "object",
                "veli"
              ],
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "scopes"
        ],
        "type": "object"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "scopes": {
      "items": {
        "enum": [
          "food",
          "food2",
          "textile",
          "object",
          "veli"
        ],
        "type": "string"
      },
      "type": "array"
    },
    "source": {
      "enum": [
        "Agribalyse 3.2",
        "Custom",
        "Ecobalyse",
        "Ecoinvent 3.9.1",
        "Ecoinvent 3.11",
        "Ginko 2025",
        "WFLDB",
        "Woolmark",
        "forwast",
        "PastoEco"
      ],
      "type": "string"
    },
    "unit": {
      "enum": [
        "kg",
        "t⋅km",
        "kWh",
        "MJ",
        "L",
        "item",
        "m2",
        "m3"
      ],
      "type": "string"
    },
    "waste": {
      "maximum": 1,
      "minimum": 0,
      "type": "number"
    }
  },
  "required": [
    "categories",
    "displayName",
    "id",
    "scopes",
    "source"
  ],
  "type": "object"
}

=== MTES-MCT/ecobalyse-data/lci_catalog/agribalyse-3-2/sparkling-75cl-wine-glass-bottle-green-cork-stopper-835g.json
{
  "activityName": "Sparkling wine, 75cl | Packaging System, N0, All, Glass bottle (green) 835g with cork stopper {FR} U",
  "categories": [
    "material",
    "packaging",
    "packaging_type:bottle"
  ],
  "displayName": "Bouteille en verre vert de 835g pour vin effervescent - 75cl",
  "id": "a59a1304-9607-48ea-83f9-7bbec6cb9fc2",
  "metadata": [
    {
      "id": "7ea25190-9d2c-4085-81cb-8e7d1f9bdaa8",
      "scopes": [
        "food2"
      ]
    }
  ],
  "scopes": [
    "food",
    "food2"
  ],
  "source": "Agribalyse 3.2",
  "unit": "item"
}

=== MTES-MCT/ecobalyse-data/data/lci_catalog/ecoinvent-3-9-1/medium-voltage-power-north-america.json
{
  "activityName": "electricity, medium voltage//[RNA] market group for electricity, medium voltage",
  "categories": [
    "energy"
  ],
  "comment": "Ancien identifiant (12/2024): elec-medium-region-north-america.",
  "displayName": "Électricité moyenne tension, Amérique du nord",
  "elecMJ": 0,
  "heatMJ": 0,
  "id": "6911c87b-6cf9-5b33-be9a-e50a9e132575",
  "metadata": [
    {
      "id": "7c299e26-d5bd-4129-bbc6-c925a07d1a7e",
      "scopes": [
        "object",
        "food2"
      ]
    }
  ],
  "scopes": [
    "textile",
    "object",
    "veli",
    "food2"
  ],
  "source": "Ecoinvent 3.9.1",
  "unit": "kWh",
  "waste": 0
}

=== MTES-MCT/ecobalyse-data/lci_catalog/ecobalyse/petit-suisse-10pct-fat-v1.json
{
  "activityName": "Petit suisse, 10pct fat, variant 1, CMAPS {GLO} U",
  "categories": [
    "ingredient",
    "material"
  ],
  "displayName": "Fromage frais type petit suisse, nature, 10% MG environ FR",
  "id": "2548a428-3112-44ea-aa78-dc6458178fc5",
  "metadata": [
    {
      "alias": "petit-suisse-10pct-fat-fr",
      "defaultOrigin": "France",
      "displayName": "Fromage frais type petit suisse, nature, 10% MG environ FR",
      "id": "77df15d5-7c82-4866-8b0c-5490a8d77228",
      "inediblePart": 0,
      "ingredientCategories": [
        "dairy_product"
      ],
      "ingredientDensity": 1,
      "rawToCookedRatio": 1,
      "scenario": "reference",
      "scopes": [
        "food",
        "food2"
      ],
      "transportCooling": "always",
      "visible": false
    }
  ],
  "scopes": [
    "food",
    "food2"
  ],
  "source": "Ecobalyse"
}

=== MTES-MCT/ecobalyse-data/lci_catalog/ecobalyse/pasta-glo-es-2025.json
{
  "activityName": "Pasta, dried, from durum wheat, at plant, from GLO wheat and ES elec",
  "categories": [
    "ingredient",
    "material",
    "material_type:other_food_items"
  ],
  "displayName": "Pâtes ES (blé GLO + élec ES) (2025)",
  "id": "2d0ef86b-3865-57f9-a896-e45c8f680b2c",
  "metadata": [
    {
      "alias": "pasta-glo-es",
      "cropGroup": "BLE TENDRE",
      "defaultOrigin": "EuropeAndMaghreb",
      "displayName": "Pâtes ES (blé GLO + élec ES)",
      "explain": "Pâtes avec blé GLO et transformation élec ES",
      "id": "9bead6d1-5941-40b0-ae58-3d51bb690ba8",
      "inediblePart": 0.2,
      "ingredientCategories": [
        "grain_processed"
      ],
      "ingredientDensity": 0.72,
      "rawToCookedRatio": 2.259,
      "scenario": "import",
      "scopes": [
        "food",
        "food2"
      ],
      "transportCooling": "none",
      "visible": true
    }
  ],
  "scopes": [
    "food",
    "food2"
  ],
  "source": "Ecobalyse"
}

=== MTES-MCT/ecobalyse-data/lci_catalog/agribalyse-3-2/hdpe.json
{
  "activityName": "Polyethylene, high density, granulate {RER}| production | Cut-off, S - Copied from Ecoinvent U",
  "categories": [
    "packaging"
  ],
  "displayName": "Polyéthylène haute densité",
  "id": "174ad4a0-c386-5a34-abba-c7cc1839701b",
  "metadata": [
    {
      "id": "77d32048-2678-4942-bf52-0eb150dab3f9",
      "scopes": [
        "food2"
      ]
    }
  ],
  "scopes": [
    "food",
    "food2"
  ],
  "source": "Agribalyse 3.2"
}

=== MTES-MCT/ecobalyse-data/lci_catalog/custom/sawing-kiln-drying-wood.json
{
  "categories": [
    "transformation",
    "material_type:wood"
  ],
  "comment": "Energy consumptions based on Ecobalyse litterature review with an average scenario hypothesis (main sources : FAO national statistics  + Swedish manufacturing plants statistics  + Canada manufacturing plants statistics + Ecoinvent resources)",
  "displayName": "Sciage + séchage au four (bois)",
  "elecMJ": 216,
  "heatMJ": 1000,
  "id": "9154831a-090d-5636-81d3-ca89b8af20d2",
  "impacts": {
    "acd": 0,
    "cch": 0,
    "etf": 0,
    "etf-c": 0,
    "fru": 0,
    "fwe": 0,
    "htc": 0,
    "htc-c": 0,
    "htn": 0,
    "htn-c": 0,
    "ior": 0,
    "ldu": 0,
    "mru": 0,
    "ozd": 0,
    "pco": 0,
    "pma": 0,
    "swe": 0,
    "tre": 0,
    "wtu": 0
  },
  "metadata": [
    {
      "id": "baf8cc1a-767e-452d-b86e-e9399a99cb55",
      "scopes": [
        "object",
        "veli"
      ]
    }
  ],
  "scopes": [
    "object",
    "veli"
  ],
  "source": "Custom",
  "unit": "m3",
  "waste": 0.5
}

=== MTES-MCT/ecobalyse-data/lci_catalog/ecoinvent-3-9-1/synthetic-rubber.json
{
  "activityName": "synthetic rubber//[RER] synthetic rubber production",
  "categories": [
    "material",
    "material_type:rubber"
  ],
  "comment": "",
  "displayName": "Caoutchouc synthétique",
  "elecMJ": 0,
  "heatMJ": 0,
  "id": "5cae8f4a-125c-57a7-853b-b5648902badc",
  "metadata": [
    {
      "id": "9c5a7a8e-6483-4da8-9cc2-0a90a30cb93a",
      "scopes": [
        "object",
        "veli"
      ]
    }
  ],
  "scopes": [
    "object",
    "veli"
  ],
  "source": "Ecoinvent 3.9.1",
  "unit": "kg",
  "waste": 0
}

=== MTES-MCT/ecobalyse-data/lci_catalog/ginko-2025/pineapple-organic.json
{
  "activityName": "Pineapple, at farm, organic 2025 {CR}",
  "categories": [
    "ingredient",
    "material",
    "material_type:fruits_and_vegetables"
  ],
  "displayName": "Ananas Bio (CR)",
  "id": "1b151f8c-d72b-5e6a-837c-ac4eb4b341a6",
  "location": "CR",
  "metadata": [
    {
      "alias": "pineapple-organic",
      "cropGroup": "ARBORICULTURE",
      "cropGroupMatch": {
        "confidence": 1.0,
        "rule": "matched 'pineapple' in cropgroup.csv"
      },
      "defaultOrigin": "France",
      "displayName": "Ananas Bio",
      "id": "c52c5693-d7b8-53ff-ba1e-5a0fa6e153a2",
      "inediblePart": 0.5,
      "inediblePartMatch": {
        "confidence": 1.0,
        "rule": "Matched with Pineapple in agb_inedible.csv"
      },
      "ingredientCategories": [
        "vegetable_fresh",
        "organic"
      ],
      "ingredientDensity": 0.95,
      "ingredientDensityMatch": {
        "confidence": 1.0,
        "rule": "pineapple found in density.csv"
      },
      "rawToCookedRatio": 0.856,
      "rawToCookedRatioMatch": {
        "confidence": 1.0,
        "rule": "Matched with pineapple in cooked_to_raw.csv"
      },
      "scenario": "organic",
      "scopes": [
        "food",
        "food2"
      ],
      "transportCooling": "always",
      "transportCoolingMatch": {
        "confidence": 1.0,
        "rule": "fruit NOVA 1 → always (perishable)"
      },
      "visible": true
    }
  ],
  "scopes": [
    "food",
    "food2"
  ],
  "source": "Ginko 2025",
  "unit": "kg"
}
